### ISSUE TITLE
RA2_World, nodes not initialized, NameError: name 'gamma_node01' is not defined

### ISSUE THREAD

**Issue by anvilvapre** [Zawaro/blender-cnc-templates#3]
I was curious and wanted to see if i could load your project.

In the function `RA2_World` some of the nodes are not initialized/set before being used. 

I.e. the first three, i did not try fixing the rest. They do seem to be set for RA1_World.

```
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:38:01)                                                             
Error: Python: Traceback (most recent call last):                                                                       
  File "/opt/blender/blender_openra/blender-cnc-templates/cyclesx/main.py", line 14, in <module>
    ra2_scene = RA2()                                                                                                   
  File "/opt/blender/blender_openra/blender-cnc-templates/cyclesx/scenes.py", line 457, in __init__
    world = RA2_World(self.world_texture_path, self.world_texture_name, self.suffix)       
  File "/opt/blender/blender_openra/blender-cnc-templates/cyclesx/world_materials.py", line 66, in RA2_World
    world.node_tree.links.new(gamma_node01.outputs[0], background_node01.inputs[0])       
NameError: name 'gamma_node01' is not defined

```

```
Error: Python: Traceback (most recent call last):
  File "/opt/blender/blender_openra/blender-cnc-templates/cyclesx/main.py", line 14, in <module>
    ra2_scene = RA2()
  File "/opt/blender/blender_openra/blender-cnc-templates/cyclesx/scenes.py", line 457, in __init__
    world = RA2_World(self.world_texture_path, self.world_texture_name, self.suffix)
  File "/opt/blender/blender_openra/blender-cnc-templates/cyclesx/world_materials.py", line 77, in RA2_World
    world.node_tree.links.new(tex_env_node.outputs[0], mixrbg_node.inputs[1])
NameError: name 'tex_env_node' is not defined. Did you mean: 'tex_sky_node'?
```

```
Error: Python: Traceback (most recent call last):
  File "/opt/blender/blender_openra/blender-cnc-templates/cyclesx/main.py", line 14, in <module>
    ra2_scene = RA2()
  File "/opt/blender/blender_openra/blender-cnc-templates/cyclesx/scenes.py", line 457, in __init__
    world = RA2_World(self.world_texture_path, self.world_texture_name, self.suffix)
  File "/opt/blender/blender_openra/blender-cnc-templates/cyclesx/world_materials.py", line 82, in RA2_World
    world.node_tree.links.new(mapping_node01.outputs[0], tex_env_node.inputs[0])
NameError: name 'mapping_node01' is not defined. Did you mean: 'mapping_node02'
```

https://github.com/Zawaro/blender-cnc-templates/blob/29a09683feabec66839b34ee606681e4936425ab/cyclesx/world_materials.py#L66

**Comment by Zawaro** [comment]
Fixed by the big refactor (shared/world_materials.py). All node variables are now defined before use in `Base_World`.

- Fix commit: 61e1ab9 (consolidate shared modules, add compat layer, tests, CI/CD)
- PR: https://github.com/Zawaro/blender-cnc-templates/pull/11

Closing as stale — RA2_World now delegates to Base_World, no NameError path remains.

**Comment by Zawaro** [comment]
Verified fixed in current codebase; closing.
